# Generated by Django 4.0 on 2021-12-24 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='your own personal name', max_length=30)),
                ('middle_name', models.CharField(help_text='your own second name', max_length=30)),
                ('last_name', models.CharField(help_text='your family name', max_length=30)),
                ('summary', models.TextField(help_text='Tell us a little about yourself', null=True)),
                ('date_of_birth', models.DateField()),
                ('date_created', models.DateField(auto_now=True)),
                ('date_updated', models.DateField(auto_now_add=True)),
                ('state_of_origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form.state')),
            ],
        ),
    ]
