# Generated by Django 4.0 on 2021-12-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='state',
            new_name='State',
        ),
        migrations.AlterField(
            model_name='information',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
